.TH FUSESMB 1 "August 5, 2005"

.SH NAME
fusesmb \- Mount network neighbourhood

.SH SYNOPSIS
.B fusesmb
.I mountpoint
.RI [options]
.SH DESCRIPTION
.B fusesmb
is a Network Neighborhood (Samba shares) filesystem. It works like smbfs, but instead of accessing one share at a time, all computers and workgroups are accessible at once from a single filesystem mount.

.SH OPTIONS
.B fusesmb
accepts the following options:
.TP
.B \-h
Show summary of options.

.SH FILES
.TP
.I ~/.smb/fusesmb.conf
Configuration file for \fBfusesmb\fP. Make sure that this file is only readable by the owner or else fusesmb will not start.

.TP
.I ~/.smb/fusesmb.cache
A sorted list of all workgroups, servers and shares found on your network.

.SH "SEE ALSO"
.BR fusesmb.conf (5)

.SH AUTHOR
Vincent Wagelaar <vincent@ricardis.tudelft.nl>.
